package com.hockey.core;

import java.util.List;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.hockey.core.dao.TeamRepository;
import com.hockey.core.model.Team;

//   @CrossOrigin(origins = "http://localhost:4200")
@CrossOrigin(origins = "*") // allow requests from any origin
@RestController
@RequestMapping("api")
public class MainController {
  Logger logger = Logger.getLogger(MainController.class);
  
  
  @Autowired // This means to get the bean called teamRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private TeamRepository teamRepository;

  
  @GetMapping(path="/all")
  public List<Team> getAllTeams() {
    // This returns a JSON or XML with the users
	logger.debug("getAllTeams has been reached");
	return (List<Team>) teamRepository.findAll();
  }
}