version: '3.7'
services: 
    api_service:
        build: .
        ports:
         - "8085:8085" 
        depends_on: 
           db:         
              condition: service_healthy

    db:    
        image: mysql:latest
        volumes:
            - "mysql-data:/var/lib/mysql"
        environment:
           MYSQL_USER: springuser
           MYSQL_PASSWORD: Qazwsx21$$
           MYSQL_DATABASE: db_nhl
           MYSQL_ROOT_PASSWORD: Qazwsx21$$
           TZ: "US/Eastern"

        ports:
         - "3306:3306" 
   
        expose: 
         - "3306"  
        
        healthcheck:
           test: "/usr/bin/mysql --user=springuser --password=Qazwsx21$$ --execute \"SET GLOBAL time_zone = 'US/Eastern';\""
           interval: 2s
           timeout: 20s
           retries: 10
        
volumes:
    mysql-data: 