apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendspring
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backendspring
  template:
    metadata:
      labels:
        app: backendspring
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        name: backendspring
        ports:
        - name: backendspring
          containerPort: 8085
        env:  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldeployment
spec: 
  selector:
    matchLabels:
      app: mysqldeployment
  template:
    metadata:
      labels:
        app: mysqldeployment
    spec:
      containers:
        - name: "test-mysql"
          image: "mysql/mysql-server"
          ports:
            - containerPort: 3306
              protocol: "TCP"
          env:
            - name: "MYSQL_USER"
              value: "springuser" 
            - name: "MYSQL_PASSWORD"
              value: "Qazwsx21$" 
            - name: "MYSQL_DATABASE"
              value: "db_nhl"  
            - name: "MYSQL_HOST"
              value: "10.0.0.114" 
            - name: "MYSQL_PORT"
              value: "3306"       
---
