apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboothockey-ingress
spec:
  rules:
    - host: backend.minikube.springboot
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backendspring
                port:
                  number: 8085  
