apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-deployment"
  labels: 
    app: "{{ .Chart.Name }}-deployment"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}-deployment"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}-deployment"
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        name: hockeyimage
        ports:
          - containerPort: 8085
            protocol: TCP
        env:  
          - name: "MYSQL_USER"
            value: "springuser" 
          - name: "MYSQL_PASSWORD"
            value: "Qazwsx21$" 
          - name: "MYSQL_DATABASE"
            value: "db_nhl2024"  
          - name: "MYSQL_HOST"
            value: "10.0.0.114" 
          - name: "MYSQL_PORT"
            value: "3306"       
---
