name: Docker Image CI

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:
    inputs:
      APP_VER:
        description: "Input from the user for the Image Version"
        required: true
    secrets:
      DOCKER_USER: 
        required: true
      DOCKER_PASS: 
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from default branch 
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub 
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }} 
         
      - name: Extract metadata (tags, labels) for Docker 
        id: meta
        uses: docker/metadata-action@v3
        with: 
            images: skyler21/kubernetes

      - name: Build and push Docker image 
        uses: docker/build-push-action@v3
        with: 
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
               