name: Docker Image CI

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:
    inputs:
      APP_VER:
        description: "Input from the user for the Image Version"
        required: true
    secrets:
      DOCKER_USER: 
        required: true
      DOCKER_PASS: 
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from default branch 
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub 
        uses: docker/login-action@
        with: 
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }} 
         